/**
 * All the possible user badges.
 * @interface
 */

export interface Badges {
    '1979-revolution_1'?: string
    '60-seconds_1'?: string
    '60-seconds_2'?: string
    '60-seconds_3'?: string
    'H1Z1_1'?: string
    'admin'?: string
    'ambassador'?: string
    'anomaly-2_1'?: string
    'anomaly-warzone-earth_1'?: string
    'anonymous-cheerer'?: string
    'artist-badge'?: string
    'axiom-verge_1'?: string
    'battlechefbrigade_1'?: string
    'battlechefbrigade_2'?: string
    'battlechefbrigade_3'?: string
    'battlerite_1'?: string
    'bits'?: string
    'bits-charity'?: string
    'bits-leader'?: string
    'brawlhalla_1'?: string
    'broadcaster'?: string
    'broken-age_1'?: string
    'bubsy-the-woolies_1'?: string
    'chatter-cs-go-2022'?: string
    'clip-champ'?: string
    'creator-cs-go-2022'?: string
    'cuphead_1'?: string
    'darkest-dungeon_1'?: string
    'deceit_1'?: string
    'devil-may-cry-hd_1'?: string
    'devil-may-cry-hd_2'?: string
    'devil-may-cry-hd_3'?: string
    'devil-may-cry-hd_4'?: string
    'devilian_1'?: string
    'duelyst_1'?: string
    'duelyst_2'?: string
    'duelyst_3'?: string
    'duelyst_4'?: string
    'duelyst_5'?: string
    'duelyst_6'?: string
    'duelyst_7'?: string
    'enter-the-gungeon_1'?: string
    'eso_1'?: string
    'extension'?: string
    'firewatch_1'?: string
    'founder'?: string
    'frozen-cortext_1'?: string
    'frozen-synapse_1'?: string
    'game-developer'?: string
    'getting-over-it_1'?: string
    'getting-over-it_2'?: string
    'glhf-pledge'?: string
    'glitchcon2020'?: string
    'global_mod'?: string
    'heavy-bullets_1'?: string
    'hello_neighbor_1'?: string
    'hype-train'?: string
    'innerspace_1'?: string
    'innerspace_2'?: string
    'jackbox-party-pack_1'?: string
    'kingdom-new-lands_1'?: string
    'moderator'?: string
    'moments'?: string
    'no_audio'?: string
    'no_video'?: string
    'okhlos_1'?: string
    'overwatch-league-insider_1'?: string
    'overwatch-league-insider_2018B'?: string
    'overwatch-league-insider_2019A'?: string
    'overwatch-league-insider_2019B'?: string
    'partner'?: string
    'power-rangers'?: string
    'predictions'?: string
    'premium'?: string
    'psychonauts_1'?: string
    'raiden-v-directors-cut_1'?: string
    'rift_1'?: string
    'rplace-2023'?: string
    'samusoffer_beta'?: string
    'staff'?: string
    'starbound_1'?: string
    'strafe_1'?: string
    'sub-gift-leader'?: string
    'sub-gifter'?: string
    'subscriber'?: string
    'superhot_1'?: string
    'superultracombo-2023'?: string
    'the-surge_1'?: string
    'the-surge_2'?: string
    'the-surge_3'?: string
    'this-war-of-mine_1'?: string
    'titan-souls_1'?: string
    'treasure-adventure-world_1'?: string
    'turbo'?: string
    'twitch-intern-2023'?: string
    'twitchbot'?: string
    'twitchcon2017'?: string
    'twitchcon2018'?: string
    'twitchconAmsterdam2020'?: string
    'twitchconEU2019'?: string
    'twitchconEU2022'?: string
    'twitchconEU2023'?: string
    'twitchconNA2019'?: string
    'twitchconNA2020'?: string
    'twitchconNA2022'?: string
    'twitchconNA2023'?: string
    'tyranny_1'?: string
    'user-anniversary'?: string
    'vga-champ-2017'?: string
    'vip'?: string
    'warcraft'?: string


}

